meal_plan/urls.py
from django.urls import path
from meal_plan.views import (
    MealPlanCreateView,
    MealPlanDeleteView,
    MealPlanDetailView,
    MealPlanListView,
    MealPlanUpdateView,
)

urlpatterns = [
    path("", MealPlanListView.as_view(), name="meal_plan_list"),
    path(
        "<int:pk>/detail/",
        MealPlanDetailView.as_view(),
        name="meal_plan_detail",
    ),
    path(
        "new/",
        MealPlanCreateView.as_view(),
        name="meal_plan_create",
    ),
    path("<int:pk>/edit/", MealPlanUpdateView.as_view(), name="meal_plan_edit"),
    path(
        "<int:pk>/delete/",
        MealPlanDeleteView.as_view(),
        name="meal_plan_delete",
    ),
]

scrumptious/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans/", include("meal_plan.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meal_plan/models.py
from django.db import models
from django.conf import settings


# Create your models here.


class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField()
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    recipes = models.ManyToManyField("recipes.Recipe", related_name="recipes")

    def __str__(self):
        return self.name

meal_plan/forms.py
from socket import fromshare
from django import forms

from meal_plan.models import MealPlan


class MealPlanForm(forms.ModelForm):
    class Meta:
        model = MealPlan
        fields = [
            "name",
            "date",
            "recipes",
        ]

meal_plan/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from meal_plan.models import MealPlan

# Create your views here.


class MealPlanListView(LoginRequiredMixin, ListView):
    model = MealPlan
    template_name = "meal_plan/list.html"
    paginate_by = 3

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanDetailView(DetailView):
    model = MealPlan
    template_name = "meal_plan/detail.html"

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "meal_plan/new.html"
    fields = ["name", "recipes", "date"]

    def form_valid(self, form):
        # save meal plan but dont put in database
        plan = form.save(commit=False)

        # assign owner to meal plan
        plan.owner = self.request.user

        # now, save to database
        plan.save()

        # save all many to many relationshops
        form.save_m2m()

        # redirect to detail page for the meal plan
        return redirect("meal_plan_detail", pk=plan.id)


class MealPlanUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "meal_plan/edit.html"
    fields = ["name", "date", "recipes"]

    def get_success_url(self) -> str:
        return reverse_lazy("meal_plan_detail", args=[self.object.id])


class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "meal_plan/delete.html"
    success_url = reverse_lazy("meal_plan_list")

meal_plan/templates/meal_plan/delete.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <div class="delete-form">
      <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ mealplan.name }}"?</p>
        {{ form.as_p }}
        <div>
          <button class="button">Delete</button>
        </div>
      </form>
    </div>
  </main>
{% endblock content %}

meal_plan/templates/meal_plan/detail.html
{% extends 'base.html' %}


{% block content %}
  <main class="recipe-detail">
    <div>
      <a href="{% url 'meal_plan_edit' mealplan.id %}">Edit</a>
      <a href="{% url 'meal_plan_delete' mealplan.id %}">Delete</a>
    </div>
    <h1>{{ mealplan.name }}</h1>
    <p>
      To be served on {{ mealplan.date }}
    </p>
    <h2>Recipes</h2>
    <ol>
      {% for recipe in mealplan.recipes.all %}
        <li><a href="{% url 'recipe_detail' recipe.id %}">{{ recipe.name }}</a></li>
      {% endfor %}
    </ol>
  </main>
{% endblock content %}

meal_plan/templates/meal_plan/edit.html
{% extends 'base.html' %}

{% block content %}
  <main class="meal-plan-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Update</button>
      </div>
    </form>
  </main>
{% endblock content %}

meal_plan/templates/meal_plan/list.html
{% extends 'base.html' %}


{% block pagination %}
<a href="{% url 'meal_plan_create' %}">Create a meal plan</a>
    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
    </div>
{% endblock pagination %}

{% block content %}
  <main class="recipe-grid">
    {% for meal_plan in mealplan_list %}
      <div class="recipe-card">
        <h2 class="recipe-card-title">
          <a href="{% url 'meal_plan_detail' meal_plan.pk %}">{{ meal_plan.name }}</a>
        </h2>
        <p class="recipe-card-date">{{ meal_plan.date }}</p>
      </div>
    {% endfor %}
  </main>
{% endblock content %}

meal_plan/templates/meal_plan/new.html
{% extends 'base.html' %}

{% block content %}
  <main class="meal-plan-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Create</button>
      </div>
    </form>
  </main>
{% endblock content %}